version: '3'

services:
  api:
    container_name: fn-screener-backend_api
    build:
      context: .
    env_file: .env
    environment:
      NODE_ENV: production
      MONGO_DB_URI: mongodb://mongo:27017
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: >
      sh -c "
      ./docker/wait-for-it.sh mongo:27017 -t 60
      && npm ci
      && npm run build
      && npm run setup:dist
      && npm run start:dist
      "
    volumes:
      - .:/code

  mongo:
    container_name: fn-screener-backend_mongo
    image: mongo:4.4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: fnScreenerBackendLocal
      MONGO_INITDB_ROOT_PASSWORD: fnScreenerBackendLocal
    volumes:
      - './docker/mongo_data:/data/db'
    ports:
      - 27017:27017

  swagger:
    container_name: fn-screener-backend_swagger
    image: swaggerapi/swagger-ui:v3.38.0
    environment:
      CONFIG_URL: swagger-ui.config.json
    volumes:
      - ./api-docs:/usr/share/nginx/html/api-docs
      - ./swagger-ui.config.json:/usr/share/nginx/html/swagger-ui.config.json
    ports:
      - 8080:8080

  swagger-validate:
    container_name: fn-screener-backend_swagger-validate
    image: node:12-alpine
    volumes:
      - ./api-docs:/api-docs
    command: npx swagger-cli validate api-docs/${API_VERSION:-v1}.yml
